---
# --- VARIABLES GLOBALES DEL PROYECTO PHOENIX ---
cloudflare_tunnel_token: "eyJhIjoiY2Q1MmIyYmIzMWRiMDNmOWU1YjI4N2QxMjhlYTEzY2YiLCJ0IjoiOWQ1NDhlM2UtYmExNS00MjgxLWI0MDctZWFlMDAxNDg5YTg3IiwicyI6IlkyTm1ZVGhoTXpndE1qQmpOaTAwTmpBMUxXRTVaakV0TkRKbE4yUXlPR05tTUdZMyJ9"
# Software Base (Role: Common)
common_packages:
  - htop
  - git
  - curl
  - net-tools
  - vim
  - ufw
  - tree  # ¡Aprovechamos para añadir una nueva herramienta útil!

# Seguridad (Role: Security)
security_ssh_port: 22
security_allowed_tcp_ports:
  - '80'   # HTTP
  - '443'  # HTTPS
  # Si mañana necesitas el 8080, solo lo añades aquí.