---
- name: ğŸ“¦ Crear grupo para Prometheus Node Exporter
  group:
    name: node_exporter
    system: yes

- name: ğŸ‘¤ Crear usuario para Prometheus Node Exporter
  user:
    name: node_exporter
    group: node_exporter
    system: yes
    shell: /bin/false
    create_home: no

- name: â¬‡ï¸ Descargar Node Exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: âš™ï¸ Instalar binario de Node Exporter
  copy:
    src: /tmp/node_exporter-1.7.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: yes

- name: ğŸ“„ Crear servicio Systemd
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
  notify: restart_node_exporter

- name: ğŸš€ Asegurar que Node Exporter estÃ¡ corriendo y habilitado
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes

- name: ğŸ›¡ï¸ Abrir puerto 9100 en UFW
  ufw:
    rule: allow
    port: '9100'
    proto: tcp
    comment: 'Permitir metricas para Argus'
