---
- name: Actualizar cach√© de apt y actualizar paquetes
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Instalar herramientas esenciales definidos en variables
  apt:
    name: "{{ common_packages }}"
    state: present
