---
- name: Instalar dependencias para aÃ±adir repositorios
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Crear directorio para llaves (keyrings)
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Descargar llave GPG oficial de Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: AÃ±adir repositorio de Docker a Apt
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Instalar Docker CE y plugins
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: AÃ±adir usuario sysadmin al grupo docker (para usarlo sin sudo)
  user:
    name: sysadmin
    groups: docker
    append: yes

- name: ðŸ”“ Permitir Registry Inseguro (Local)
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries" : ["10.2.84.60:5000"]
      }
  notify: reiniciar_docker  # AsegÃºrate de tener un handler para reiniciar docker